#####################################################################################
#### NOTE: head over to `builds.yaml` to define what builds you'd like to run. ####
#### (i.e., datasets and subsampling schemas)  ####
#####################################################################################

# This analysis-specific config file overrides the settings in the default config file.
# If a parameter is not defined here, it will fall back to the default value.

configfile:
  - defaults/parameters.yaml # Pull in the default values
  - my_profiles/n_only/builds.yaml # Pull in our list of desired builds

config:
  - sequences=data/genbank_sequences_20210405.fasta
  - metadata=data/genbank_metadata_20210405.tsv

# Set the maximum number of cores you want Snakemake to use for this pipeline.
cores: 8

# Always print the commands that will be run to the screen for debugging.
printshellcmds: True

# Always print log files of failed jobs to the screen.
show-failed-logs: True
